### ISSUE TITLE
(4) CockroachDB insert optimizations [4]

### ISSUE THREAD

**Issue by asymeon** [AuthEceSoftEng/cenote#16]

**Comment by kyrcha** [comment]
Implement the two things below initially and count times based on the performance tests (#10) for each one of the optimizations:

- [x] Add CREATE TABLE IF NOT EXISTS
- [ ] Add Redis lookup *

Instead of checking the table for the columns, add a redis lookup. The key in redis will be the table name and the value a sorted list of keys. If equals then no need to alter table or columns. If not then we continue as is now and update redis with the new columns. If redis has no key then for the first time do the expensive operation

**Comment by MichaelPap** [comment]
Before Redis, please check as an initial step if we can insert index into the table that serves the `show columns` functionality. If we see that this change has a great impact on the final time behavior (which is the case in my opinion), then we can proceed by making it as "instant" as we can by exploring Redis incorporation.
