### ISSUE TITLE
(0.5) Retrieving a target property as an array of values [0.5]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#46]
Hello,

suppose that I want to retrieve a specific target property.

The docs state that I have to use the target_property parameter to my query. This works fine, but returns an array of objects with key-value pairs, e.g.  `[{"key": 1}, {"key": 2}, {"key": 3}, ...]`

Is it possible to get directly array of values? So to get a result like `{"key": [1, 2, 3, ...]}`. My only concern is that this may help save some bandwidth particularly when big data are involved and consequently make my requests faster.

Tangentially related to this: can I request more than one target properties simultaneously in the same request?

Is there something I am missing?

Thanks!

**Comment by kyrcha** [comment]
The only issue I see in the Array is that we should also take into account that the key might be missing from an event among the retrieved ones. So we must fill it with null. Also if more target properties are retrieved the Arrays should have the same length, since different keys might be missing from different events.

I propose to keep array of objects as it is now and add a query parameter to transform the array of objects into an object of arrays in the response.

**Comment by iamnapo** [comment]
Fixed in https://github.com/AuthEceSoftEng/cenote-api/commit/be668d152f2fb6e20052ae203588260d48036fe1.

- I added the param `concat_results` (more info in /docs).
- To request more target properties set the query like: 
	```js
	"target_property": "key1,key2,..."
	```

(Will push docs and feature to production soon)
