### ISSUE TITLE
(3) Getting duplicates in submitted data [3]

### ISSUE THREAD

**Issue by tsakiridis** [AuthEceSoftEng/cenote#72]
Hello!

When I am submitting multiple data, some of them are stored twice. I can't understand why :(

Please see the attached file (python script as .txt) as a minimal example. It creates a new event called test and pushes some data. It then retrieves the same data only to find that some duplicates have been inserted.

If you run it multiple times you may see that the number of duplicates is different at each run.

Let me know if you need any further clarifications.

Thanks!

[cenote-duplicates.txt](https://github.com/AuthEceSoftEng/cenote/files/4814595/cenote-duplicates.txt)

**Comment by thdiaman** [comment]
@iamnapo @MichaelPap Can you check this out and let us know if it is a bug of Cenote? Thanks!

**Comment by iamnapo** [comment]
An assertion test like this (writing X entries and then checking that exactly X entries have been written) runs 9 times after each deployment (the latest is at: https://travis-ci.com/github/AuthEceSoftEng/cenote/builds/172482121). So I'm not sure why exactly this is happening.

I'll see if I can manage to recreate it and I'll let you know.

@johnantonn Have you experienced this in eeris? Do you have any clues?

**Comment by mstamatiadou** [comment]
Maybe this has to do with the fact that no timestamp value is given in the dataset (in the .txt data file), so cenote assigns the default timestamp (now) in milliseconds? And maybe this is due to rounding to the closest integer (in milliseconds). 

As far as it comes to eeris (speaking for my side), I have not faced such an issue because we always concretely assign a timestamp to the measurement posted. 

Hope this helps

**Comment by johnantonn** [comment]
Hello,

@iamnapo @mstamatiadou actually, I can see it happening in eeris event collections as well, see the screenshot below from the _**test_project**_:
![installations-events](https://user-images.githubusercontent.com/8168416/85388282-929c1300-b54e-11ea-82af-fb81c68587a3.png)

It happens in my personal test collections as well, where for example I send a single event for a device once an hour, from the screenshot below it seems that the events for the same deviceid/timestamp are stored twice:
![Screenshot_4](https://user-images.githubusercontent.com/8168416/85389376-012da080-b550-11ea-9f8a-d8e316f194c6.png)

**Comment by mstamatiadou** [comment]
Check this example: 

```
{
            "active": 380.396087646,
            "reactive": 19.9854373932,
            "current": 1.73634231091,
            "voltage": 229.98550415,
            "frq": 49.99,
            "uuid": "917fc672-4b3b-4f6d-91cd-eff00a7d975f",
            "cenote$created_at": 1592407520786,
            "cenote$timestamp": 1592407415000,
            "cenote$id": "5a3fc47b-26e0-4421-813c-e2b76ad7107f"
        },
 {
            "active": 380.620361328,
            "reactive": 19.5682048798,
            "current": 1.7370057106,
            "voltage": 229.984970093,
            "frq": 49.99,
            "uuid": "830cab52-1eca-4e13-a187-79d09e6d8c43",
            "cenote$created_at": 1592407520716,
            "cenote$timestamp": 1592407414000,
            "cenote$id": "d48105b3-d839-4746-bd6b-d5bd43e43ac6"
        }
```

Here, in this case we have explicitly assigned "cenote_timestamp" value, given by the meter in advance. If we don't do this, then cenote will give the current timestamp to both created_at and cenote_timestamp. So, if you transform these 2 created_at values from above, you will see that they are both rounded to the same datetime. That's why I'm saying that this might be the reason behind this issue.

**Comment by johnantonn** [comment]
Hello again,

After a preliminary analysis of the projects and event collections (including the ones we have for eeris production and my own for testing) I observed the following:
- At around **1pm Friday 19/06** the multiple records start to occur in cenote.
- This affects every event collection I searched, including my own test collections for eeris, meazon and the new collections which split the data per installation.
- Until that point (Friday 12:55pm), I could not find any multiple recording of events.
- This behavior is not consistent. Even now, some records that are sent are written only once, while others, a few moments later, might be multiple-recorded.
- I had faced a similar issue during the first days of trying to install a local instance of cenote, and the issue was related to kafka and the way it streamed the data from/to producers/consumers.

FYI: The latest changes related to the new schema (per installation collections) were deployed on Thursday afternoon and affected both the topology and the API.

![eeris-test-installationsX](https://user-images.githubusercontent.com/8168416/85398394-d5191c00-b55d-11ea-8767-d178101e71ee.png)

**Comment by johnantonn** [comment]
Hi all,

Has anyone observed the same behavior during the past week or today, after the reboot of cenote?

@tsakiridis Does the issue persist?

**Comment by tsakiridis** [comment]
Hi @johnantonn,

thanks for your work.

The last instance of duplicate data appears to be on Tuesday 23rd of June. The above attached script also no longer produces duplicates. Everything looks ok as far as I can tell.

**Comment by johnantonn** [comment]
Closing this since the issue did not persist, but we should keep our eyes open for a re-visit..

**Comment by tsakiridis** [comment]
Hi all,

sorry for resurrecting this one, but I'm noticing again duplicates in the vital project starting around September 30th, 2020.

To be as precise as I can be (because we submit data at 6 hour intervals), the problem started sometime between 8:55:52 AM, 30/09/2020 and 2:56:21 PM, 30/09/2020; these are taken from cenote$created_at so I am not sure about the timezone (EEST or UTC).

Can somebody please kindly check their own projects and tell me if this is an issue with cenote or if the issue is on my end? Sorry, but I cannot test my above code to see if the data are written twice as there presently is a delay between the time a POST request is accepted and the time the data are consumed.

Thanks in advance!

Nikos

**Comment by johnantonn** [comment]
Hello @tsakiridis , 

Thanks for letting us know. Indeed this seems to be a general issue, I am currently looking into it.

**Comment by johnantonn** [comment]
Cenote recovery process finished. Should work as expected.
