### ISSUE TITLE
(5) Implement online outlier detection [5]

### ISSUE THREAD

**Issue by kyrcha** [AuthEceSoftEng/cenote#9]
Based on [this](https://github.com/AuthEceSoftEng/cenote/blob/master/OUTLIERS.md)

**Comment by MichaelPap** [comment]
Given that the outlier detection can be very tricky as we may face race conditions, I propose the following strategy:

1. Create a functional table into cenote that will hold the information regarding the parameters of the outliers (in order for the whole procedure to be incremental)
2. The server should trigger the outlier detection update procedure (in certain time intervals) by sending a certain type of event that will be handled by one bold at a time. This is crucial in order to avoid race conditions.

So, the proposed approach needs the following:
- Write a server script to send the respective events in certain intervals (i.e. every 1 hour) 
- Write the corresponding code that will be executed by the bolts that will handle the outlier detection events.

**We need to consider the following:** 
- Which parameters are we going to hold in the outlier detection table?
- How many columns per bolt (one or multiple?). This is important as in the case of 1 column/bolt, we may get all system resources for the outlier detection and thus no write can occur at that time. 


There are certain optimizations that can be done in the context of this process, which will be handled after the main functionality is implemented.

@kyrcha Do you agree?

**Comment by kyrcha** [comment]
@MichaelPap What do you mean by functional table?

I don't mind to have a process to update the values in a system (every hour or every 1000 events), instead of doing it in parallel, but I believe it should be in an in memory system so that it is fast and not in the database that would require a new connection and extra space.

**Comment by MichaelPap** [comment]
@kyrcha By stating functional table, I mean a dedicated table inside cenote that will hold the information of the outlier detection mechanism. Each row of this table will correspond to a certain column of a given collection (table) and each column will be a parameter that we need to update incrementally (e.g. min, max, q1, number of instances, etc...)

The in-memory system can hold the values of this table in order for the read queries to be fast, but the table itself needs to be inside cenote (I think...), in order to have data persistence.

**Comment by MichaelPap** [comment]
So, the extra step needed in order to put the in-memory system (e.g. Redis) in the loop is to store the values of the functional table into redis cache whenever it gets updated. So, whenever a query involves outliers detection, we will instantly get the values to be filtered out.

**Comment by kyrcha** [comment]
Based on the document I wrote we need only mean and variance. I believe we should first check whether we can update the values using atomic operations in REDIS or [transactions](https://redis.io/topics/transactions) since these data are derived and are not facts stored inside the system. In this way we can have updates near real-time...and perhaps occasionally store them in cockroach as milestones for feature use.

**Comment by kyrcha** [comment]
Code for running average is ready. I have used 100 threads to calculate the running average of values between 0 and 999 using REDIS and transactions (pipelines in python-redis). It seems to work without loosing anything. We should check if the same is true for bolts.

```
from multiprocessing import Pool
import redis


# Atomic operations
def f(x):
    # print(x)
    r = redis.Redis(host='localhost', port=6379, db=0)
    r.incrby('sum', x)

# transactional operations
# https://stackoverflow.com/questions/12636613/how-to-calculate-moving-average-without-keeping-the-count-and-data-total
def g(x):
    # print(x)
    r = redis.Redis(host='localhost', port=6379, db=0)
    pipe = r.pipeline()
    pipe.incr('n')
    multiply(keys=['avg', 'n'], args=[x], client=pipe)
    pipe.execute()

if __name__ == '__main__':
    rmain = redis.Redis(host='localhost', port=6379, db=0)
    print(rmain.set('sum', 0))
    print(rmain.set('avg', 0))
    print(rmain.set('n', 0))
    lua = """
    local avg=redis.call('get',KEYS[1])
    local n=redis.call('get',KEYS[2])
    avg = avg-avg/n + ARGV[1]/n
    redis.call('set', KEYS[1], avg)
    """
    multiply = rmain.register_script(lua)
    p = Pool(100)
    p.map(f, range(100))
    p.map(g, range(1000))
    print(rmain.get('sum'))
    print(rmain.get('avg'))
```

**Comment by kyrcha** [comment]
Also with redis persistence https://redis.io/topics/persistence snapshots we can store the data every let’a say hour and leave cockroach light

**Comment by kyrcha** [comment]
Final algorithm with some refactorings and including variance/std can be found here: https://gist.github.com/kyrcha/974f662d988906023d20cadf22a8a88e
